wixplosives/engine

packages/scripts/src/application.ts
We have a wrong handing in the runNodeEnv function which causes runOptions not to pass when  the runNodeEnvironment is being called
=> Scripts: wrong options handling

packages/scripts/src/node-environments-manager.ts, packages/scripts/src/run-node-environment.ts
Socket connections will now be namespaced under the environment name, which will cause that messages from different environments don't get mixed up.
=> Com: socket scoping to environment

packages/scripts/src/application.ts, packages/scripts/src/config-middleware.ts
Response with env as id in communication middleware in order to support a standalone preview (run preview content a new tab)
=> Communication: response with env as id in communication middleware

packages/core/src/communication.feature.ts, packages/core/src/entities/feature.ts, packages/core/src/types.ts
Add running environment name to feature setups. SettingUpFeature type expose the `runningEnvironmentName` param only to universal feature setups.
=> Add running environment name to universal feature setup

packages/test-kit/src/with-feature.ts
Subscribe to newly open tabs/windows from root page and close them after test.
=> test-kit: handle tabs/windows opened by tests

packages/core/src/run-engine-app.ts
`canAccessWindow` is testing the access to `window`'s `location,search` property.
This change prevents returning `false` when `search` is an empty string.
=> refactor and export canAccessWindow function

packages/scripts/src/analyze-feature.ts
Currently loadFeaturesFromPackages searches at `['.', 'src', 'feature', 'fixtures']`, and this cannot be extended.
Added the possibility to define a root directory for feature locating meaning that if the feature I want to load is in ./my/path/to-feature.tsx, then I could provide to loadFeaturesFromPackages with `./my/path` as the base directory, and my feature will be found
=> Scripts: Allow providing feature locator a base directory for own features

.github/workflows/tests.yml
- Node 14.1.0 fixed broken puppeteer. lets see if anything else broke.
- drop Node 13.
=> infra: test on Node 14

examples/file-server/feature/file-server.server.env.ts, examples/file-server/package.json, examples/file-server/test/file-server.unit.ts, examples/multi-env/package.json, examples/multi-env/test/file-server.unit.ts, package.json, packages/scripts/src/index.ts, packages/scripts/src/ipc-environment.ts, packages/scripts/src/load-node-environment.ts, packages/scripts/src/node-environment.ts, packages/scripts/src/ws-environment.ts, packages/test-kit/package.json, packages/test-kit/src/index.ts, packages/test-kit/src/run-environment.ts
Exposed runEnvironment method which runs an environment based on a provided fs.
Method allows passing resolved context for a contextual environment, as well as config overrides
=>  Test-kit: allow running environment on given fs

packages/scripts/src/create-entrypoint.ts
Currently if the feature has multiple environment files with the same target, e.g. `feature.main.env.tsx` and `feature.preview.env.tsx` with the `web` target, both are included in the same Webpack chunk. Meaning that both environments unnecessarily load all the code designated for another environment.
Even though this unused code is not evaluated, it increases parse time and memory consumption.
This PR creates one chunk for the `.feature` file, and one chunk for each `.env` file.
In the project I'm working on this separation of chunks increased the total uncompressed
amount of code in the main environment from 19.5MB to 19.9MB, and decreased the
amount of code in the preview environment from 19.0MB to 1.8MB
There's still a lot of space for improvement, for example many of the `.feature` …
=> Separate Webpack chunks for different environments

packages/scripts/src/application.ts, packages/scripts/src/config-middleware.ts, packages/scripts/src/create-entrypoint.ts, packages/scripts/src/create-webpack-configs.ts, packages/scripts/src/engine-router.ts, packages/scripts/src/node-environments-manager.ts, packages/scripts/src/types.ts, packages/scripts/test/application.unit.ts
Currently, when using the Application API (in scripts) there is no way to build a feature (or start one) with a config.
=> scripts: allow building with provided config

packages/engineer/src/utils.ts, packages/engineer/test/dev-server.unit.ts, packages/engineer/test/gui.unit.ts
In engineer, instead of returning the instance of the running feature, when calling startDevServer, returning the feature's api
=> engineer: returning api or running dev server

packages/scripts/src/analyze-feature.ts
currently analyze-features adds to the finds redundant features
=> scripts: not pick up non-evaluated features

packages/core/src/run-engine-app.ts, packages/scripts/src/analyze-feature.ts
converting the way we load features.
now a feature definition holds only direct dependencies
=> core: feature definition contains only direct dependencies

packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/scripts/src/application.ts, packages/scripts/src/node-environments-manager.ts
Pass socket server configuration to node environment manager for `runEnvironmentInNewServer`
=> scripts: pass socket config to node-env-manager

examples/preload/globals.d.ts, packages/core-node/package.json, packages/core/src/globals.d.ts, packages/scripts/src/top-level-config-loader.ts, tsconfig.base.json, yarn.lock
- socket.io@3 references two libraries without built-in .d.ts files, so either we install it or the user will.
- using "*", to be consistent with @types packages and how they reference dependencies. "*" dedupes well in npm. yarn installs latest.
- fixed globals.d.ts in core and preload (now that .d.ts files are checked.
- fixed duplicate @types/react being installed.
- ensured topLevelConfigLoader is @types/node@14 compatible.
=> core-node: install required @types

packages/core/src/com/communication.ts
When calling a remote API, before the environment is available, we register the a callback to send the message once the environment is ready.
But the target will always be to self, which will forward message to the second environment.
This caused the communication state to be invalid in forward listening messages
=> com: avoid redundant forwarding of messages

packages/test-kit/src/create-browser-provider.ts, packages/test-kit/src/with-feature.ts
instead of pipe, which was required for previous versions
=> fix(test-kit): use puppeteer's default ws com

packages/scripts/test/application.unit.ts
- our app is dynamically loading, so we want to wait for the body to load (or we get flakiness in slower CI).
- two tests injecting stuff to Application.run() were already broken. The if statements inside the waitFor caused noop to happen, as waitFor expects a throw/rejection to retry. noop means all is good in tests, so false positive.
=> test(scripts): use waitFor; skip false-positives

examples/file-server/test/file-server.unit.ts, examples/multi-env/test/file-server.unit.ts, packages/test-kit/src/run-environment.ts
Currently we dont validate that the environment being evaluated in node, should evaluate there.
At the first phase we will warn (with the ability to throw) when running envs of wrong targets on node, and leter will throw.
Also deprecating the usage of the fs in that method
+ allow providing feature deiscovery root for compatibility
=> fix(test-kit): warn when non-node env runs on node

packages/engineer/src/cli-commands.ts
Exposing 2 extra flags to the build command from the cli: `withExternalFeatures` and `fetchExternalFeatures`.
=> feat(scripts): exposing flags to build command

packages/scripts/src/create-entrypoint.ts, packages/scripts/src/create-webpack-configs.ts
The current way we map the external features in webpack is by mapping the feature files, and not the actual requests.
=> fix(external-features): properly mapping feature requests

packages/engineer/src/application-proxy-service.ts, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/src/utils.ts, packages/engineer/test/dev-server.unit.ts, packages/scripts/src/application.ts, packages/scripts/src/utils/external-features.ts, packages/scripts/test/application.unit.ts
currently resolving external features base path from the application base path, but the more correct way to do it is if there is an engine config present - from it.
=> fix(scripts): resolve external features from proper path

packages/scripts/src/application.ts
The run command id application.ts doesn't serve the external features by default. this is a bug
=> fix(scripts): serve external features on run by default

packages/scripts/src/create-entrypoint.ts, packages/scripts/src/create-webpack-configs.ts
When testing current functionality in electron applications, it fails. This fixes the fails fetching external features in electron
=> fix(scripts): fetch external features in electron

packages/engineer/src/cli-commands.ts
currently cli parses to flags as strings and not boolean.
=> fix(engineer): parsing boolean arguments in build command

packages/core/src/com/types.ts, packages/core/test/node/api-type-check.spec.ts
closes #571
otherwise, using `ValuePromise<R>` causes `() => boolean` to get re-wrapped as `() => Promise<true> | Promise<false>`
=> fix(core): keep promise-returning fn as-is

packages/scripts/src/create-webpack-configs.ts, packages/scripts/src/index.ts, packages/scripts/src/webpack-html-attributes-plugins.ts
adding crossorigin attribute to the environment's auto generated html
=>  fix: loading html scripts with crossorigin

packages/engineer/src/feature/gui.dev-server.env.ts, packages/scripts/src/application.ts, packages/scripts/src/create-webpack-configs.ts
`infrastructureLogging` used to affect the way `webpack-dev-middleware` prints the stats. this is no longer the case, starting with `webpack-dev-middleware@4.0.3`.
=> fix: print stats only on warnings/errors

packages/core/src/com/communication.ts, packages/core/src/com/errors.ts, packages/core/src/com/message-types.ts, packages/core/src/helpers/index.ts, packages/core/src/helpers/serialize-error.ts, packages/core/test/communication.spec.ts, packages/core/test/test-api-service.ts
Sometimes it's useful to show the error message that occurred in a remote API call to the user:
```ts
try {
await service.doThing();
} catch (error) {
setDialogError(error.message);
}
```
But currently we prefix each error with 'Remote call failed with error:', and also include the entire stack trace in the error message, which doesn't look good in the UI.
Additionally, we discard custom error properties, such as error code.
This PR changes error handing to preserve the error name, message, and custom properties. If the error is uncaught, it's useful for debugging to know from which environment it originated, and we add this extra info to `error.stack`. Chrome logs it in full to the console. Unfortunately, Firefox ignores `error.stack` and shows its own stack trace that's not derived from …
=> feat(core): preserve original error message in cross-env API calls

packages/test-kit/src/with-feature.ts
rather than hooking to the 'popup' event of every page, we can now add a single listener on the browser context to catch them all.
=> refactor(test-kit): browser context for page hook

packages/core/src/com/initializers/iframe.ts
Changed the way we change iframe's url to `replace` instead of changing `location.href`, in this way it won't affect the history stack.
Fixes [#3306](https://github.com/wixplosives/component-studio/issues/3306)
=> fix(iframe location): fix iframe location change

packages/scripts/src/application.ts
when mapping own requests to engine files in the manifest, we should not re-map to relative requests, unless the outdir is inside the base path. Otherwise resolution will fail
=> fix(scripts): map to requests only if out dir inside base dir scope

packages/core/package.json, packages/core/src/communication.feature.ts, packages/core/src/globals.d.ts, packages/core/test/webpack.config.js
- avoid using global process. instead, import it from `'process'` and map that to an empty object. `"browser"` field is picked by bundlers.
- also, ensure `process.versions.node` is truthy, for naive polyfills.
=> fix(core): improved node detection

packages/engineer/src/cli-commands.ts, packages/scripts/src/application.ts, packages/scripts/src/types.ts, packages/scripts/test/application.unit.ts
Using the featureOutDir in in build command, to point to the bundled sources of the application, and fall back to featureDiscovery root
=> fix(scripts): properly re-mapping requests in manifest file

packages/scripts/src/create-entrypoint.ts
we no longer need to normalize route to request, since it's a request to a file
=> hotfix(script): don't normalize externals route

packages/scripts/src/application.ts
After deciding that the latest version was a minor, I found a place that is not backward compatible.
Adding backward compatibility by adding the previous route middleware to response to the /external request
=> hotfix(scripts): returning the externals route

packages/scripts/src/create-webpack-configs.ts
Adding backward compatibility for external features in webpack 4
=> fix(scripts): backward compatibility for webpack 4

packages/engineer/src/cli-commands.ts, packages/scripts/src/create-entrypoint.ts
Curretly we import an empty array if there are no external features for that environment but they exist
=> fix(scripts): importing external features only if defined

packages/scripts/src/create-entrypoint.ts
We didn't take into consideration that the publicPath may be an empty string, in which case we don't need to normalize it
=> hotfix(scripts): fix public path resolution for fetching external features

packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/test/gui.unit.ts
The issue with not being able to see the project from the root of the monorepo is because we have the dashboard both as the actual dashboard and as a regular feature in the project, so we have 2 middleware serving main-dashboard.html
because the application middleware is registered first it catches the request and serves the one without the default feature being set, so we need to pass it manually.
It can basically happen with every application that serves a main-dashboard environment.
The way to resolve it is to resolve the conflict in the URL which I see several options
1. Namespace the middleware
2. Serve from different servers
3. Assume that our dashboard is the default dashboard and add it as an index - therefor solving the URL conflict.
=> fix: set main-dashboard.html as index file for engineer dashboards

packages/engineer/package.json, packages/engineer/src/feature/gui.dev-server.env.ts, packages/scripts/package.json, packages/scripts/src/create-webpack-configs.ts, packages/scripts/src/index.ts, packages/scripts/src/virtual-modules-loader.ts, yarn.lock
webpack-virtual-modules doesn't work well with webpack@5.
replaced it with custom loader solution that uses !=! to represent new virtual entry module, getting their contents from options.
=> refactor: better virtual-modules with !=!

packages/engineer/src/feature/dev-server.dev-server.env.ts
instead, directly wait for the top compiler to be done, which is only called once.
Fixes messages of "wait until bundle finished" printing in basically every flow.
=> fix: avoid waitUntilValid, as it triggers logging

packages/scripts/src/create-entrypoint.ts
got broken when code moved to Map
also listed each in own line, for readability
=> fix(scripts): correctly print feature names

webpack.config.js
and remove css-loader usage, as no css is now used within repo (and it isn't even specified as a direct dep; got it from mocha-play)
=> infra(webpack): use native asset modules

examples/multi-env/test/file-server.unit.ts, packages/test-kit/src/run-environment.ts
currently the getRunningFeature returns under the runningApi the wrong type, which cause users to use ugly castings
=> fix(test-kit)!: getRunningFeature returns proper type

packages/core/src/com/communication.ts
Class Communication contains method registerMessageHandler(target) which adds event listener to "message" events on target. 
This task adds missing removeMessageHandler method which would be used to remove event listener when we dispose some specific host.
=> feat: add removeMessageHandler method to Communication

packages/engineer/src/application-proxy-service.ts, packages/engineer/src/cli-commands.ts, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/scripts/src/analyze-feature.ts, packages/scripts/src/application.ts, packages/scripts/src/load-node-environment.ts, packages/scripts/src/remote-node-entry.ts, packages/scripts/src/types.ts
allows specifying featureDiscoveryRoot in `engine.config.js`.
=> feat(scripts): featureDiscoveryRoot via config file

.eslintignore, .eslintrc, examples/file-server/tsconfig.json, examples/multi-env/tsconfig.json, examples/node-only/tsconfig.json, examples/preload/tsconfig.json, examples/react/tsconfig.json, examples/reloaded-iframe/tsconfig.json, packages/core-node/test/tsconfig.json, packages/core/test/tsconfig.json, packages/dashboard/test/tsconfig.json, packages/engineer/test/tsconfig.json, packages/scripts/test/tsconfig.json, packages/test-kit/src/tsconfig.json, packages/test-kit/test/tsconfig.json, tsconfig.test.json
typescript-eslint's experimental project ref support is not working great.
by using a single commit test tsconfig, lint time drops significantly. we do have to build first now, in order to lint.
=> infra: simplify lint setup

packages/core/src/com/initializers/iframe.ts, packages/core/test/communication.spec.ts
There was a bug in the iframe initializer which caused api registrations which occured prior to the initialize call, to do nothing"
=> fix(core): deferred iframe initializer register env as pending

packages/core/src/com/initializers/iframe.ts
The previous version never used the src that was passed to it, only as a condition. See the compiled version:
=> fix(com): fix iframe initializer handling of src parameter

packages/scripts/src/create-entrypoint.ts, packages/scripts/test/application.unit.ts, test-fixtures/with-iframe/feature/x.feature.ts, test-fixtures/with-iframe/feature/x.iframe.env.ts, test-fixtures/with-iframe/feature/x.main.env.ts, test-fixtures/with-iframe/package.json, test-fixtures/with-iframe/tsconfig.json, tsconfig.json
after the minor refactor with the config fetching, I accidentally hard-coded the word 'configs' rather then using the `publicConfigsRoute` variable.
Added a test
=> hotfix: not handling custom config routes properly

.eslintrc, package.json, tsconfig.lint.json
`typescript-eslint` gets OOM when we're using it's project refs support.
using `compilerOptions.paths` just for the lint flow allows us to get a nicer IDE behavior without requiring us to build in order to lint.
=> infra: IDE-friendly typescript-eslint refs workaround

packages/test-kit/src/with-feature.ts
After a discussion with @RomanYarik we came up with this solution of having the option to override the default behavior of not allowing any uncaught errors on with a custom handler.
=> feat(with-feature): providePageErrorsHandler

packages/scripts/src/create-entrypoint.ts, packages/scripts/src/utils/external-features.ts
because this is in a string template it wasn't type-checked.
We must use scopedName there
=> fix(external-features): use scoped name for proper feature resolution

packages/scripts/src/create-webpack-configs.ts
avoid building electron environments if no feature name was specified
=> fix(scripts): no electron if no feature name

packages/scripts/src/create-webpack-configs.ts
Currently we try to require respresolve requests to loaders, fixing that by ignoring them
=> fix(external-features): ignore loader requests

packages/core/src/com/communication.ts
in cases where the forwarded message is a dispose message, we want to ignore it, since the engine initiates the disposing call to other environments once it receives the dispose message for itself.
this caused dispose messages to be handled as listen calls
=> fix(com): forwarding listen messages properly

packages/core-node/src/ipc-host.ts, packages/core-node/test/node-com.unit.ts, packages/scripts/test/application.unit.ts, packages/test-kit/src/detached-app.ts
currently, if process is closed, we still try to send messages to it.
fixing that in a similar manner to what was done in the socket server socket disconnection handling
=> fix(core-node): handle process disconnection

packages/runtime-node/src/config-locators.ts, packages/runtime-node/src/index.ts, packages/runtime-node/src/node-environments-manager.ts, packages/scripts/src/config-middleware.ts
currently same code is duplicated across many projects, and each time the implementation is "similar but not quite the same" as the function in the config middleware, which had the original behavior.
moved this method to `@wixc3/engine-runtime-node`  since the node-environment-manager uses pretty much the same (worse) implementation.
=> refactor(scripts): export config location function and unify usage

packages/scripts/package.json, packages/scripts/src/create-webpack-configs.ts, yarn.lock
currently we use `require.resolve` when trying to understand if the request is to a feature file when crating the webpack config for the external feature. 
This will fails when browser fields are configured.
Using `@file-services/resolve` since this resolver handles browser fields
=> fix(script): resolve external requests using `@file-services/resolve`

packages/electron-scripts/src/commands/build.ts, packages/engineer/src/cli-commands.ts, packages/scripts/src/application.ts
Currently build command only returns the compilation stats. modifying it to also return the features, configurations and resolved environments for that build.
This allows also fixing the issue with entries which should be filtered out, appears in the electron entrypoint
=> feat(scripts): return the build data from build command

packages/core/src/com/communication.ts, packages/core/test/node/com.spec.ts
Currently forwarding errors of forwarded messages doesn't work well
fixing that by changing the order or registration of callbacks and handling errors
=> fix(com): properly forwarding errors

packages/core/src/com/communication.ts
messages were emitted only if callback id is provided, which caused the emitOnly functions to fail
=> hotfix(com): adjust forwarding to previous behavior

packages/test-kit/src/with-feature.ts
To access window.performance.memory in headless mode, you must add the `--enable-precise-memory-info` flag when launching chromium.
See StackOverflow: https://stackoverflow.com/a/57829821/13994821
=> feat(test-kit): supported performance.memory in headless withFeature

packages/electron-scripts/src/commands/build.ts
* These copied symlinks are broken, and  causes failure of signing process in Mac
=> fix(electron-scripts): don't copy .bin folder of electron host

packages/core/src/com/communication.ts, packages/core/test/node/com.spec.ts
Currently after environment is closed, nothing cleans the open communication handlers
=> fix(com): clean hanging handlers on env disposal

examples/file-server/src/test/file-server.ix.ts, examples/react/src/test/react.ix.ts, packages/engineer/test/gui.unit.ts, packages/test-kit/src/with-feature.ts
users of `withFeature -> getLoadedFeature` can specify whatever `navigationOptions` they want for either per-suite or per-test level
=> fix(test-kit)!: don't default to waitUntil: 'networkidle'

packages/test-kit/src/hook-page-console.ts
when serialization fails due to data not being serializable, or target already close, hookPageConsole now prints original non-formatted text instead of the unrelated error
=> fix(test-kit): fallback to non-formatted msg text

packages/test-kit/src/with-feature.ts
put the breaking change behind an env flag (SKIP_NETWORK_WAIT) to allow downstream to adapt first.
=> fix(test-kit): back to waitUntil: 'networkidle'

packages/core/src/communication.feature.ts, packages/core/src/entities/feature.ts, packages/core/src/entities/service.ts, packages/core/src/entities/value.ts, packages/core/src/runtime-engine.ts, packages/core/src/symbols.ts, packages/core/src/types.ts, packages/core/test/node/api-type-check.spec.ts, packages/core/test/node/com.spec.ts, packages/core/test/node/runtime.spec.ts
This is the start of the effort to move the communication to a separated package also this PR will enable features to access the engine in the setup function
* Pass the `RuntimeEngine` to the `SettingUpFeature`
* Removed `getCOM` from engine runtime (remove coupling prepare for communication split)
* Removed `runningEnvironmentName` (can be accessed via runtime engine)
* Introduce `Value` entity for local provided values
This is a major version
=> chore: engine communication cleanups

packages/core/src/entities/map-slot.ts, packages/core/src/entities/slot.ts
after looking at usages I found many `[...slot].(map|find|reverse)` usages that are redundant loops. 
this PR adds the ability to get the underling registry bucket as readonly
=> feat: Add ability to get readonly buckets from slots

packages/core/src/com/communication.ts
- Added ability to get registered environments using communication API
- Removed `disposedEnvironments` property in order to be able to relaunch disposed env
=> feat(extend-envs-api): Added new methods to work with registered environments

packages/dashboard/src/components/dashboard.st.css, packages/dashboard/src/components/dashboard.tsx, packages/dashboard/src/components/dependency-graph/dependency-graph.tsx, packages/dashboard/src/components/feature-graph.tsx, packages/dashboard/src/components/sidebar/sidebar.tsx
Bugfixes: 
* Dependency graph not shown on first load
* Dependency graph is now being evaluating based on URL params
* Dependency graph is stacking graphs if the dependency input not cleared entirely (empty string)
Refactor:
* Decoupled `Dashboard` components a bit, introducing two new ones:
- `dependency-graph`
- `sidebar`
The refactor purpose is in favor of improving the UX of the dashboard, having it easier to read
=> fix(dashboard): dependency graph plus refactor

packages/electron-commons/src/initializers/electron-node.ts, packages/electron-commons/test/initializers/electron-node.spec.ts, packages/electron-node/src/initializers/node-process.ts, packages/electron/src/initializers/electron-node.ts
Changed function `initializeNodeEnvironment` to be synchronous instead of async.
The callers might need this to have immediate access to the `dispose` function.
This is needed cause, in some cases, application exit might be requested in between two moments: the environment is already spawned, and the environment did not send a callback via communication yet. Example use case: close electron application in one second after window appear. Because closing the window causes the host for the electron-renderer process to be disposed (at least I think so), the `envReady` event is not triggered via communication for the newly created environment.
In that case, the caller will never be able to dispose such env cause it will not be registered, and dispose function will not be returned. However, the …
=> feat(node-environment-initializer): Updated node environment initializer to be synchronous

package.json, packages/core/src/com/communication.ts, packages/core/src/com/types.ts, packages/core/src/entities/service.ts, packages/engineer/src/cli-commands.ts, tsconfig.base.json, yarn.lock
- add several generic constrains per new ts generics behavior
- disable lib check until socket.io is fixed https://github.com/socketio/socket.io/issues/4459
- regenerate lock file
=> chore(deps-dev): typescript@4.8.2

packages/core-node/src/ws-node-host.ts, packages/core-node/test/node-com.unit.ts, packages/core/src/com/communication.ts
fixes #1423
The main problem was that we were namespacing `handlerId` in the `subscribe` calls and not in the `unsubscribe`.
Second problem was that we were doing it inside the Node Host - as a result it was not obvious inside the `Communication` whether `handlerId` is namespaced or not in each method.
So there are 2 fixes:
1) namespace `handlerId` in both `subscribe` and `unsubscribe`
2) add transparent namespacing into `Communication`
=> fix(events): unsubscribe handlers not being invoked

packages/core-node/src/ipc-host.ts, packages/core-node/src/ws-node-host.ts, packages/core/src/com/communication.ts, packages/core/src/com/message-types.ts, packages/core/test/node/com.spec.ts
Added `forwardingChain` property to the message object so we can detect and fail on circular message forwarding.
When a message is forwarded from one env to another, we add the current instance id to a `forwardingChain` array, so we can detect if the same message comes to our instance circularly and fail this message.
=> fix(communication): Fixed circular message forwarding

packages/test-kit/src/run-environment.ts
renamed `IGetRuinnnigFeatureOptions` interface to `IGetRunnigFeatureOptions`
=> fix: typo in running feature interface

packages/engineer/src/cli-commands.ts, packages/engineer/src/utils.types.ts
public path is set to '' now by default.
Why?
* in codux I want to use bundled files from root and from path, thus I want relative assets
Why don't codux passes publicPath: '' instead of change in default param?
* there is no reason to have  / by default
=> feat!: public path default set to empty

packages/test-kit/src/with-feature.ts
also fixed the ability to override options from the suite or the test itself. renamed a few variables for clarity.
=> fix(test-kit): tracing now extracts correct test title

packages/test-kit/src/with-feature.ts
Currently, the output trace file name might be (as a default name) the test name without the first letter =>
`flaky-test => laky-test.zip`
This PR should fix it
=> fix(naming): changing tracing file default name

docs/runtime.entities.environment.md, packages/core/src/com/initializers/iframe.ts, packages/core/src/entities/feature.ts, packages/core/src/entities/slot.ts, packages/core/test/node/api-type-check.spec.ts, packages/core/test/node/env-dependencies.spec.ts, packages/electron-node/src/initializers/browser-window.ts, packages/electron-scripts/src/commands/build.ts, packages/engineer/src/utils.ts, packages/runtime-node/src/process-communication.ts, packages/scripts/src/analyze-feature/load-features-from-paths.ts, packages/scripts/src/application/application.ts, packages/scripts/src/feature-generator/feature-generator.ts, packages/scripts/test/merge.unit.ts, packages/test-kit/src/supported-browsers.ts, webpack.config.js
* run `npx prettier . --write`
* fix typo in `electron-scripts/src/commands/build` (exporting instead of exporing)
=> infra: reformat all sources using latest prettier

packages/electron-commons/src/expirable-list.ts, packages/electron-commons/src/initializers/electron-node.ts, packages/electron-commons/test/initializers/electron-node.spec.ts, packages/electron-node/src/initializers/node-process.ts, packages/electron/src/initializers/electron-node.ts
Expose environment disconnect details such as exit code, signal, and last seen error to allow engine users to handle environment crash correctly in case of an unhandled exception.
=> feat: expose environment disconnect details

packages/electron-commons/test/initializers/electron-node.spec.ts
The issue with test was that in fact, that test was not checking disposing. Because we are not passing `errorMode` from that test (it is undefined), feature is initialized with default config value for `errorMode` which is `exit`. This makes feature to do `process.exit(1)`.
So, there was a race condition between test that was disposing env and a feature that was doing process.exit(1).
the fix is to pass `no-error` for `errorMode`. in this case, feature will not crash a process and it will lasts.
also note that for windows there is no signal support, so I calculating expected result based on platform where test is running
=> fix: fixed flaky test

packages/electron-host/src/start-electron-env.ts
Remove `window-all-closed` listener that manually close the app when all windows are closed
=> refactor(electron-host): remove redundant listener

packages/core-node/src/create-application-metadata-provider.ts
Do not dispose metadata communication once the metadata is loaded cause this causes issues with IPC envs and dispose hangs
=> fix: do not dispose metadata com when metadata loaded

packages/engineer/src/feature/dev-server.dev-server.env.ts
Fix dev server mode to convert analyzed features to static feature definition to avoid issues with bypassing types as Symbol as a message between envs
=> fix: fix static feature definitions in dev server mode

packages/core/src/com/communication.ts
Communication forward message functionality can accidentally resolve wrong pending callback record if callbackId is the same. Since previously call and callbacks ids were just counters `c0` `c1` `c2` - the chances of it happening are high at the startup.
p.s. forward message functionality seemed wrong but math checks out. Just callback ids should be more unique. Environment id is nor improving uniqueness, but come in handy for debugging. 
fixes issue with workers not starting sometimes
=> fix(com): use unique message ids

examples/file-server/src/test/file-server.unit.ts, examples/multi-env/src/test/file-server.unit.ts, packages/test-kit/src/run-environment.ts, packages/test-kit/test/run-environment.unit.ts
The meat of the change is at `packages/test-kit/src/run-environment.ts` - changing getRunningFeature to shut down the feature by default once the test is done
=> chore!: getRunningFeature uses disposeAfter to engine feature by default

.mocharc.js, engine.config.js, package.json, packages/dashboard/package.json, packages/engineer/package.json, packages/runtime-node/package.json, packages/runtime-node/test/node-com.unit.ts, packages/scripts/package.json, packages/scripts/test/merge.unit.ts, packages/test-kit/package.json, packages/test-kit/test/run-environment.unit.ts, tsconfig.json, yarn.lock
- some packages already ran from dist. make sure all do
- will allow running all from root with --parallel flag
- get rid of @ts-tools/node (cjs-only) to pave the way for moduleResolution: node16
- above will also allow to dynamically import esm from cts files and improve handling of native esm in existing mechanism
=> test: execute all tests from dist

packages/test-kit/src/run-environment.ts
previous behavior: getRunningFeature would run engine.shutdown after each test with a set timeout of 1 sec
new behaviour:
getRunningFeature takes the disposeAfterTestTimeout arg (prev boolean disposeAfterTest)
which can set the disposal timeout, new default 10sec instead of 1
=> chore: getRunningFeature optionally disposal timeout arg, default 10s

packages/dashboard/src/components/sidebar/sidebar.tsx
when there's no node envs running
=> fix(dashboard): avoid rendering "0"  to ui

packages/test-kit/src/with-feature.ts
In windows, this timeout was too short and created flakiness
=> fix: increased timeout for disposal of browser ctx

packages/runtime-node/package.json, packages/runtime-node/src/core-node/create-application-metadata-provider.ts, yarn.lock
package is the only dep that gives us trouble with typescript in node16 module/moduleResolution, so remove it
=> refactor: replace memoize-one with own impl

package.json, packages/core/scripts/bundle.js, packages/core/webpack.config.test.js, webpack.config.js, yarn.lock
- we have a bundle task that occurs right before publishing (prepack).
- make sure it uses dist to support upcoming esm migration.
- allows us to remove ts-tools altogether.
=> infra(core): bundle from dist

packages/core/src/runtime-configurations.ts, packages/electron-scripts/src/engine-helpers.ts, packages/runtime-node/src/node-environments-manager.ts, packages/scripts/package.json, packages/scripts/src/config-middleware.ts, packages/scripts/src/import-fresh.ts, packages/scripts/src/load-node-environment.ts, packages/scripts/src/top-level-config-loader.ts, yarn.lock
- rewrote top-level-config-loader in the process, adding more exact types and validations
- new approach is not coupled to the module system itself
=> feat: use worker thread for fresh configs

packages/scripts/src/run-environment.ts, packages/test-kit/src/run-environment.ts
worked only because it got transpiled to commonjs's require
=> fix(config): dynamic import to work in esm as well

packages/test-kit/src/run-environment.ts
reuse original method that is available from scripts, adding just the disposeAfter
=> refactor(test-kit): avoid duplicating getRunningFeature

packages/scripts/src/create-entrypoint.ts
which also generates a require call, which we don't want when moving to esm
=> refactor(scripts): remove unused fn

packages/electron/package.json
we currently use it downstream, so allow it for now
=> fix(electron): add missing ./dist/hosts entry

packages/electron-scripts/package.json
used by downstream, so support it for now
=> fix(electron-scripts): add /dist/commands export

packages/electron-scripts/package.json, packages/electron-scripts/src/cli.ts, packages/electron-scripts/src/commands/build.ts
yargs fails quitely and is not clear about how to compose commands with typed options
=> fix(electron-scripts): use commander in CLI

packages/test-kit/src/with-feature.ts
Fixing the issue of timeout exceeded when using the option `persist: true`.
Here is an exmaple of the issue that will be fixed:
https://github.com/wixplosives/codux/actions/runs/5966393026/job/16185936650
=> fix(with-feature): increase timeout of dispose suite level page

packages/test-kit/src/with-feature.ts
Adjusting the mocha timeout to be the same as the disposables' timeout.
=> fix(with-feature): adjust suite level page timeout

packages/scripts/src/utils/resolve-module-graph.ts
`import Package, { type A, type B } from 'package';` was detected as type-only and ignored
=> fix(scripts): correct case of misdetected type import

packages/electron-scripts/src/commands/start.ts, packages/engineer/bin/engineer.js, packages/engineer/package.json, packages/engineer/src/application-proxy-service.ts, packages/engineer/src/cli-bootstrap.ts, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/src/utils.ts, packages/scripts/src/analyze-feature/find-features.ts, packages/scripts/src/analyze-feature/load-features-from-paths.ts, packages/scripts/src/application/application.ts, packages/scripts/src/import-fresh.ts, packages/scripts/src/index.ts, packages/scripts/src/resolve-exec-argv.ts, packages/scripts/src/types.ts, packages/scripts/src/utils/resolve-module-graph.ts, packages/test-kit/src/forked-process-application.ts, packages/test-kit/src/with-feature.ts
when engine.config.js specifies "require" and/or "buildConditions", these are now applied to the engineer process and any worker/child process it starts.
=> fix(engineer): apply conditions/require hooks to node

packages/scripts/src/run-environment.ts
"extensions" and "conditions" were not passed
=> fix(scripts): pass options to runEngineEnvironment

packages/scripts/src/utils/paths.ts, packages/scripts/test/application.unit.ts
to better support running against sources, where the specifier might end with .ts or .tsx.
for both .ts and .js, we don't mind the specifier being more specifiic. it's making it easier to resolve.
=> fix(scripts): avoid removing specifier extension

packages/electron-scripts/src/commands/start.ts
in dev-time, we want these to propagate via process.execArgv
=> fix(electron-scripts): propagate conditions/requires

packages/engineer/src/cli-bootstrap.ts
- ensure we await "exit" and fail when appropriate
- this regressed when we moved to using worker threads
=> fix(engineer): fail process when worker fails

packages/engine-cli/bin/engine.js, packages/engine-cli/src/create-environments-build-configuration.ts, packages/engine-cli/src/engine-build.ts, packages/runtime-node/src/node-env-manager.ts, packages/scripts/src/create-entrypoint.ts, packages/scripts/src/create-node-entrypoint.ts, packages/scripts/src/create-web-entrypoint.ts
This PR focus on running our main project in the same mode (cjs)
It add support for running in both modes but currently uses `require` instead of import (only in the new node flow).
=> feat: running is cjs

packages/core/src/polyfills/report-error-polyfill.ts, packages/core/src/runtime-main.ts
Added reportError polyfill to allow applications and are using native `reportError` to execute feature setup.
=> fix: added reportError polyfil

packages/engine-cli/src/cli.ts
allow passing runtime args as json to the new esbuild cli
=> feat: support runtimeArgs from cli

packages/test-kit/src/with-feature.ts
This PR adds a `resetContextBetweenTests` configuration flag for `withFeature` to set if the browser context is recreated for each test or shared between tests - defaults to `true`
=> fix: run tests in fresh context by default

packages/core/src/runtime-engine.ts
This PR exposes the running promise on runtime engine so we can wait for it when needed.
=> feat: expose running promise on runtime engine

packages/core/src/com/communication.ts, packages/core/src/com/environment-disconnected-error.ts, packages/core/src/com/index.ts, packages/core/test/communication.spec.ts, packages/core/test/node/com.spec.ts, packages/runtime-node/test/node-com.unit.ts
Since most places want to ignore a disconnect error now they can do it easily
* Removed unnecessary `handleReady` call when calling `envReady` add an environment to pending state
* Better error when rejecting a callback (include origin message)
=> feat: added specific disconnect error

packages/engine-cli/src/engine-build.ts, packages/scripts/src/utils/environments.ts, packages/test-kit/src/engine-app-manager.ts
Also add `electronMainEnvs` to the return of `getExportedEnvironments` to be used to create configurations for build
=> refactor: remove unused configName

packages/engine-cli/src/create-entrypoints.ts, packages/engine-cli/src/create-environments-build-configuration.ts, packages/engine-cli/src/engine-build.ts
Entrypoints can be cached and save the analyzeFeatures step which is almost the same time as the build.
=> refactor: extract create entry points from build config

packages/engineer/src/cli-commands.ts, packages/runtime-node/src/remote-node-environment.ts
Reused base `engineCommandBuilder` duplicate `--inspect` options cause `commander` new version to throw
=> feat: fix commander issues with new version

packages/engine-cli/src/engine-build.ts
in watch mode if we start with a broken build. we still run the dashboard
=> fix: continue run after initial build failed.

packages/engine-cli/src/create-environments-build-configuration.ts
So when using esm bundle the devtools work very hard in order to show the `Module` keys in the scopes panel. using iife fixes that and we don't acctualy use the esbuild entry bundle as importable files (library)
=> fix: slow debug

packages/engine-cli/src/cli.ts, packages/scripts/src/types.ts
This PR allows the engine config to declare additional cli runtimeArgs embedded in the engine command.
This is not ideal because it can collide but I have a check to prevent it. maybe we can prefix them...but not for now.
Also added config and feature aliases.
=> feat: allow engine config to define cli flags

packages/core/src/com/communication.ts, packages/core/src/com/initializers/socket-server.ts, packages/core/test/node/com.spec.ts, packages/runtime-node/src/node-environments-manager.ts
In the case of forward message between source env (processing), forwarder env (manager) and target env (main).
if the manager has the main environment as pending it will now wait until the target will be resolved to send any messages.
* loosen the type for `handleReady` to allow manual management  
TODO:
=> fix: forward respect pendingEnvs

packages/engine-cli/src/cli.ts, packages/engine-cli/src/create-entrypoints.ts, packages/engine-cli/src/create-environments-build-configuration.ts, packages/engine-cli/src/engine-build.ts, packages/engine-cli/src/resolve-build-configurations.ts, packages/engine-cli/src/top-level-config-plugin-esbuild.ts
This PR address missing `staticBuild` option in the new esbuild flow.
When building targets that requires fully static build like electron we need to build the config files to disk. 
This PR enables this feature in the esbuild flow.
This PR also fixes a build in the config loader when the `outDir` is absolute.
=> feat: enable static build

packages/core/src/helpers/web.ts, packages/core/src/types.ts, packages/core/test/helpers.spec.ts, packages/scripts/src/create-web-entrypoint.ts
For the abomination. Providing entry options by other means than the search params will allow to keep the iframe url clean which is vital when running the full app instead of a board.
=> feat(core): allow passing entry options via script query

packages/engine-cli/src/cli.ts, packages/engineer/src/application-proxy-service.ts, packages/engineer/src/cli-commands.ts, packages/scripts/package.json, packages/scripts/src/index.ts, packages/scripts/test/application.unit.ts
This PR removes all non type exports from webpack done via engine-scripts.
The bigger job is to remove all webpack related code that is soon going to be dead code.
=> infra!: remove webpack from scripts index

packages/engine-cli/src/create-environments-build-configuration.ts, packages/scripts/src/types.ts
This will allow the plugins coming from extrnal application to know the if they are running in dev mode
=> feat: pass in the dev mode to build plugins

packages/test-kit/src/with-feature.ts
hotfix - engineer is dead. we don't assume consumer install it anymore
=> fix: move engineer usage to not run in module scope.

packages/engine-cli/README.md
Fix markdown formatting and update `buildTargets` to reflect the option of `electron`
=> docs(engine-cli): fix table and update `buildTargets` type

eslint.config.mjs, examples/file-server/src/fixtures/run.config.ts, examples/file-server/src/test/file-server.it.ts, examples/multi-env/src/test/multi-env.it.ts, guides/docs/entities/engine.md, packages/core/src/entities/feature.ts, packages/core/test/node/env-dependencies.spec.ts, packages/core/test/node/runtime.spec.ts, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/src/utils.ts, packages/runtime-node/src/ipc-environment.ts, packages/runtime-node/src/node-environment.ts, packages/runtime-node/src/node-environments-manager.ts, packages/runtime-node/src/process-communication.ts, packages/runtime-node/src/worker-thread-entry.ts, packages/runtime-node/test/node-environments-manager.unit.ts, packages/scripts/src/config-middleware.ts, packages/scripts/src/create-node-entrypoint.ts, packages/scripts/src/create-web-entrypoint.ts, packages/scripts/src/run-environment.ts, packages/scripts/src/types.ts, test-fixtures/engine-multi-feature/src/fixtures/fixture1.config.ts, test-fixtures/engine-multi-feature/src/fixtures/variant/variant1.config.ts, test-fixtures/engine-multi-feature/src/fixtures/variant/variant2.config.ts, test-fixtures/engine-single-feature/src/feature/x.config.ts, test-fixtures/static-base-web-application/src/base.config.ts, test-fixtures/using-config/src/fixtures/alternative.config.ts
newer react hooks lint rules now sees this use call and thinks it's a hook call outside of a component introduce Feature.configure to avoid this issue entirely
=> feat: introduce Feature.configure as an alias to Feature.use

packages/test-kit/src/with-feature.ts, packages/test-kit/test/sanitize-file-path.unit.ts
Fixes #2545 
Fixes the logic of sanitising the screenshots path. 
The current logic replaces every ':' with a '-' which on windows leads to a path 'C-\Users\...' instead of 'C:\Users\...'. 
This PR adds a lookbehind to the regex so it skips the ':' if it goes after a capital letter which is a first symbol in the path
=> fix(test-kit): tests screenshots path is broken on windows

packages/core/src/com/communication.ts, packages/core/src/com/logs.ts
This helps to know the source of the message that was in flight while the environment disconnected
=> feat: add the message that was rejected by environment disconnection

packages/core/src/runtime-engine.ts, packages/core/test/node/runtime.spec.ts
when the `catch` scope is being triggered in the `run` function, the catch will execute:
```
await this.shutdown();
```
If shutdown fails for some reason we have no information of what happened.
Adding an extra catch is for adding the missing information.
=> fix: handle error being thrown in shutdown of run

packages/scripts/src/resolve-exec-argv.ts, packages/scripts/src/types.ts
like require, but uses `--import` instead of `--require`
=> feat(engine-config): introduce "import" field

packages/engine-cli/src/analyze-command.ts, packages/engine-cli/src/cli.ts, packages/engine-cli/src/engine-build.ts, packages/engine-cli/src/entrypoint-files.ts, packages/engine-cli/src/esbuild-html-plugin.ts, packages/engine-cli/src/launch-dashboard-server.ts, packages/engine-cli/src/resolve-runtime-options.ts, packages/engine-cli/src/start-dev-server.ts, packages/runtime-node/src/metadata-files.ts, packages/test-kit/src/link-test-dir.ts
- no need for file-services in places that import file-services/node directly and dont use the extended APIs
- import-style fixes for native esm
=> refactor: use node apis directly where possible

packages/engine-cli/src/engine-build.ts, packages/engine-cli/src/types.ts
ensure it allows passing in functions without warning about T being able to instantiate with an extended type
=> refactor(config): correct OverrideConfigHook type

examples/cross-iframe/src/feature/configured-iframe.main.env.ts, examples/cross-iframe/src/test/cross-iframe-driver.ts, examples/cross-iframe/src/test/cross-iframe.it.ts, packages/core/src/com/initializers/iframe.ts, packages/core/src/runtime-main.ts, packages/core/src/types.ts
now, it will be possible to add to the iframe
```
<script data-engine-run-options="fetch-options-from-parent=true" src="./preview.web.js"></script>
```
or start the iframe with src of `./preview.web.js?fetch-options-from-parent=true`
then use `installRunOptionsInitMessageHandler` on the side of the parent window to have a working iframe env.
It will be used to decouple id generation from iframe dom node creation.
Note: iframe initialization in the engine since we have a [tech debt here](https://github.com/wixplosives/codux/issues/24381). We have an initializer directly in codux and we need to move it back to make sense.
=> feat(iframe): get run option from parent

packages/core/src/entities/feature.ts, packages/core/src/runtime-engine.ts, packages/core/src/runtime-feature.ts, packages/core/test/node/api-type-check.spec.ts, packages/core/test/node/runtime.spec.ts
This PR introduces an `optionalDependencies` configuration option for defining features. 
Optional dependencies will only be initialized and made available if another feature includes them in its (required) `dependencies` definition. This ensures that a feature can leverage another feature dynamically, based on its availability in the current running "flavor."
=> feat(core): support feature optional dependencies

packages/engine-cli/src/cli.ts, packages/engine-cli/src/engine-build.ts, packages/engine-cli/src/import-fresh.ts, packages/engine-cli/src/launch-dashboard-server.ts, packages/runtime-node/src/node-env-manager.ts
`engine-cli` used to have 3 config modes:
1. `require` - was actually doing a direct `import()` to the config (was a `require()` call before the move to esm)
2. `watch` - bundles config files into cjs bundles. this was (and still is) broken when the config module, or any of the files it imports use esm-specific syntax (e.g import.meta).
3. `fresh` - this used `import()` via a freshly created worker_thread. it allowed getting the "current" value of a config file (in dev time), meaning you don't have to watch. it got broken when we moved to esm.
#2629 removed the first two and fixed the third. this caused a speed regression downstream, as tests imported configs over and over in a non-cached manner.
with this PR, we now have 3 modes again:
1. `import` - same functionality as before, but a …
=> fix: reintroduce watch and direct import of config files

packages/engine-cli/src/engine-build.ts, packages/engine-cli/src/launch-dashboard-server.ts, packages/engine-cli/src/types.ts
This fix the issue of always showing main.html env in log
=> feat: enhance dashboard server launch with correct entry point logging

packages/core/src/com/communication-errors.ts, packages/core/src/com/communication.ts, packages/core/src/com/message-types.ts, packages/core/test/node/com.spec.ts, packages/runtime-node/test/node-com.unit.ts
This PR fixes recoonect issue with event dispatchers when environmant was removed we did not clean the listeners on the servies.
I added removeListener key requirement for the service config for now. let's make sure we all use `declareComEmitter`
=> fix: remove dispatchers from their registration when we clear an environment

packages/core/src/com/hosts/base-host.ts, packages/runtime-node/src/node-env-manager.ts, packages/runtime-node/test-kit/entrypoints/a.node.ts, packages/runtime-node/test-kit/entrypoints/b.node.ts, packages/runtime-node/test-kit/feature/envs.ts, packages/runtime-node/test-kit/feature/test-feature.a.env.ts, packages/runtime-node/test-kit/feature/test-feature.b.env.ts, packages/runtime-node/test-kit/feature/test-feature.ts, packages/runtime-node/test-kit/feature/types.ts, packages/runtime-node/test-kit/tsconfig.json, packages/runtime-node/test/node-env.manager.unit.ts, packages/runtime-node/test/tsconfig.json, tsconfig.json
Problem: 
1) two node envs started by node env manager cannot communicate without without going through client
2) all worker messages being broadcasted to all registered ws clients
Example
Fix:
forward messages on worker parent level to desired worker directly via host communication which only purpose is to forward messages to a correct environment.
=> fix(runtime node): node env manager to not broadcast node messages to web envs and allow communication between node envs

packages/core/src/com/communication.ts, packages/core/src/com/helpers.ts, packages/core/test/node/com.spec.ts
This PR adds handling for env reconnect:
- a `subscribeToEnvironmentReconnect` to allow getting events of env that is re-connected, for example when an iframe is reloaded.
- auto reconnect for event listeners
=> feat: handle env reconnect

packages/core/src/com/communication.ts, packages/core/test/node/com.spec.ts
This PR fixes a reconnect when the host is not just reloaded, but destroyed and replaced with a new one
=> fix: handle reconnect with different host
