packages/core/src/communication.feature.ts
nested ifs were harder to read.
=> engine-core: simplify com feature initialization

packages/scripts/src/application.ts, packages/scripts/src/cli.ts, packages/scripts/test/application.unit.ts
Adding port option on application start and close
=> Scripts: 'port' option for http server

packages/scripts/src/application.ts
=> scripts: stop tracking closed sockets

packages/core/src/entities/env.ts
adding a method to retrieve a child environment from a contextual env
=> Core: Locate contextual child environments by id

packages/core/src/entities/config.ts, packages/core/src/entities/feature.ts, packages/core/src/run-engine-app.ts, packages/core/src/runtime-engine.ts, packages/core/src/types.ts, packages/scripts/src/analyze-feature.ts, packages/scripts/src/types.ts
now using `Feature`/`RuntimeFeature` directly
=> core/scripts: types cleanup

packages/scripts/src/top-level-config-loader.ts
fix invalid cache cleaning in configs
=> Scripts: fix static config loaders

packages/core-node/test/node-com.unit.ts
Fixing wrong feature disposal order
=> Core(node): fixing unit tests disposal

packages/core/src/com/communication.ts, packages/scripts/src/application.ts, packages/scripts/src/cli.ts, packages/scripts/src/node-environments-manager.ts
+ allow to modify topology for environments during run time
+ changing the way node environments exposes running port
=> Com: allow to listen to environment readiness

packages/core/src/com/communication.ts, packages/core/src/com/hosts/base-host.ts, packages/core/src/com/hosts/event-emitter.ts, packages/core/src/com/hosts/index.ts, packages/core/src/com/hosts/ws-client-host.ts, packages/core/src/com/index.ts, packages/core/src/com/initializers/socket-server.ts, packages/core/src/communication.feature.ts, packages/core/test/node/com.spec.ts
Adding an event emitter host to communication
=> Com: adding event emitter host

packages/scripts/templates/package.json.tmpl
Update feature template to use wcs-scripts instead of ts-pack
=> Update feature template to use wcs-scripts instead of ts-pack

packages/scripts/src/create-webpack-configs.ts
Currently when deciding which environments to bundle, and how, we don't take into consideration the resolved contexts and the fact that 'bundled' environments can be contextual.
=> Scripts: don't bundle not resolved contextual environments

packages/scripts/src/utils/resolve-from.ts
node 12+, which is what we support
=> scripts: refactor resolveFrom to official node api

packages/core/src/com/types.ts, packages/scripts/src/create-webpack-configs.ts
+ generating html for electron-renderer targets
=> Core: adding support in electron-main environment

packages/test-kit/src/with-feature.ts
these are uncaught errors and should fail the test
=> test-kit: don't allowErrors in withFeature

packages/core/src/com/types.ts, packages/core/src/types.ts
found using the RC. verified as working in downstream project as well
=> fix: type fixes for ts3.9

packages/scripts/src/create-webpack-configs.ts
Currently we are bundling all possible environments in cases when feature name is not provided.
Fixing that to bundle only **used** environments
=> Scripts: proper context resolution

packages/core/src/entities/feature.ts, packages/core/src/run-engine-app.ts, packages/core/src/runtime-engine.ts, packages/core/test/node/api-type-check.spec.ts, packages/core/test/node/runtime.spec.ts
=> core: make run*() async and waiting

packages/scripts/src/cli.ts, packages/scripts/src/config-middleware.ts, packages/scripts/src/utils/resolve-from.ts
=> scripts: deprecate resolveFrom

examples/electron-app/package.json, package.json, yarn.lock
=> chore(deps-dev): upgrade to latest stable

packages/scripts/src/cli.ts
commander's behavior around boolean options is confusing.
=> fix: engine cli correctly handles explicit false

packages/core/src/com/communication.ts
To help to load large projects on slower machines
=> increase communication callback timeout to 5 min

packages/scripts/src/create-webpack-configs.ts
currently electron-main environments, while they don't need bundling
=> scripts: not bundling electron-main env

packages/scripts/src/create-entrypoint.ts
=> scripts: refactor create-entrypoint for re-usage

packages/scripts/src/application.ts
after https://github.com/wixplosives/engine/pull/451 we converted all feature loader's dependencies to be only the direct ones, but did not handle that in `--singleFeature` mode which relied on that
=> bug-fix(scripts): single feature mode dependency retrieval

package.json, packages/core-node/package.json, packages/core-node/src/ws-node-host.ts, packages/core-node/test/node-com.unit.ts, packages/core/package.json, packages/core/src/com/hosts/ws-client-host.ts, packages/core/src/com/initializers/socket-server.ts, packages/engineer/package.json, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/src/feature/dev-server.feature.ts, packages/engineer/src/utils.ts, packages/scripts/package.json, packages/scripts/src/application.ts, packages/scripts/src/launch-http-server.ts, packages/scripts/src/node-environments-manager.ts, packages/scripts/src/types.ts, yarn.lock
adjust code to breaking changes
=> chore(deps): socket.io@3

packages/engineer/src/cli.ts, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/src/feature/dev-server.feature.ts, packages/engineer/src/utils.ts, packages/scripts/src/application.ts, packages/scripts/src/cli.ts, packages/scripts/src/types.ts
allow to pass path to a webpack config to build the application with
=> feat: allow providing webpack config for building engine application

packages/scripts/src/application.ts, packages/scripts/src/node-environments-manager.ts
the reversed order in createDisposables is imperative for proper cleanup of complex environments.
=> fix(scripts): proper cleanup in two more places

examples/preload/test/all.ix.ts, examples/preload/test/utils.ts, packages/engineer/package.json, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/src/feature/gui.dev-server.env.ts, packages/scripts/src/application.ts, packages/test-kit/src/create-browser-provider.ts, yarn.lock
- for better forward compatibility with webpack@5, as we work to use/support it
=> chore(deps): webpack-dev-middleware@4

packages/core/src/com/initializers/worker.ts, packages/scripts/src/create-entrypoint.ts
allows loading the worker's bundle from another origin
=> feat(core): initialize Worker using a Blob

examples/react/package.json, yarn.lock
update to next version of react-refresh-webpack-plugin in react example and regenerate lockfile
=> chore: update deps

packages/engineer/src/cli-commands.ts, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/scripts/package.json, packages/scripts/src/application.ts, packages/scripts/src/create-webpack-configs.ts
revert from writing actual files, so we can avoid cleanup for now
=> infra(scripts): use virtual-modules-plugin

packages/test-kit/package.json, packages/test-kit/src/utils/index.ts, packages/test-kit/src/utils/trace.ts, packages/test-kit/src/with-feature.ts, packages/test-kit/test/trace.unit.ts, packages/test-kit/test/tsconfig.json, tsconfig.json
+ make a bit stricter types for getLoadedFeature
=> feat(test-kit): support playwright tracing

packages/engineer/src/feature/gui.dev-server.env.ts
=> fix(engineer): print correct dashboard url

packages/dashboard/src/components/dashboard/dashboard.tsx
not useful yet, and causes major slowdown to rendering
=> feat(dashboard): hide feature graph by default

packages/test-kit/src/run-environment.ts
so that featureDiscoveryRoot is auto-loaded from config
=> feat(test-kit): support engine.config in getRunningFeature

packages/core/src/entities/feature.ts, packages/core/test/node/runtime.spec.ts
currently when calling dispose multiple times, might cause dispose function to be called multiple times
=> fix(core): dispose only once

packages/engineer/src/feature/gui.dev-server.env.ts, packages/scripts/src/create-entrypoint.ts
`features.web.js`, `features.webworker.js`, etc
=> feat: bundle feature files into a single bundle

packages/test-kit/src/with-feature.ts
Reverts wixplosives/engine#991
=> Revert "feat(with-feature): providePageErrorsHandler"

packages/test-kit/src/with-feature.ts
naive mechanism to allow certain error messages to not fail the tests. others will still fail as expected.
this is *not* as flexible as the previous handler api, and that's actually on purpose. we'd like to lean towards the strict side as much as possible to avoid "real" unhandled logic errors (as opposed to ones our applications want to passthrough on purpose).
=> feat(test-kit): add allowedErrors for withFeature

package.json, packages/test-kit/package.json, yarn.lock
Reverts wixplosives/engine#996
=> Revert "chore(deps): bump sinon from 11.1.2 to 12.0.0"

packages/core/src/com/communication.ts, packages/core/test/communication.spec.ts
currently forwarding messages is missing functionality when forwarding a forwarded message
=> fix(com): fix communication forwarding

packages/core/src/com/communication.ts, packages/core/test/communication.spec.ts
Reverts wixplosives/engine#1017
=> Revert "fix(com): fix communication forwarding"

packages/test-kit/src/hook-page-console.ts, packages/test-kit/src/with-feature.ts
ensure we don't hold any playwright instance alive
=> fix(test-kit): remove error/console listeners post test

packages/core/src/com/communication.ts, packages/core/test/node/remote-service-com.spec.ts
=> fix: Avoid multiple event handlers of the same instance

packages/core/src/com/communication.ts, packages/core/test/node/com.spec.ts
Currently communication not forwarding dispose messages
=> fix(communication): forward dispose messages

examples/file-server/src/test/file-server.ix.ts, examples/react/src/test/react.ix.ts, packages/engineer/test/gui.unit.ts, packages/test-kit/src/with-feature.ts
Reverts wixplosives/engine#1164
=> Revert "fix(test-kit)!: don't default to waitUntil: 'networkidle'"

packages/core/src/entities/feature.ts
WIP of the `Feature` documentation in effort to provide devs a better coding experience.
Some props are lacking documentation at this point and docs will be added later on.
=> docs(feature): start of documentation

packages/core/src/com/hosts/ws-client-host.ts
Enable Socket.IO to pass Cookies to the connection
=> Enable cookie authentication for socket.io

packages/core/src/com/communication.ts
=> fix(code-style): fix missing semicolons

packages/core/src/com/communication.ts
=> chore(communication): Fixed methods and properties spelling

examples/cross-iframe/src/test/cross-iframe.ix.ts, packages/engineer/test/dev-server.unit.ts, packages/engineer/test/gui.unit.ts, packages/test-kit/src/create-browser-provider.ts, packages/test-kit/src/with-feature.ts
refactored several tests to use locators instead
=> fix(test-kit): avoid waiting until networkidle by default

packages/runtime-node/src/environments.ts, packages/runtime-node/test/node-environments-manager.unit.ts
when you have 100+ feature, this printed unordered list doesn't make sense
=> feat: sort printed feature list

package.json, packages/scripts/package.json, yarn.lock
Reverts wixplosives/engine#1601
=> Revert "chore(deps): bump rimraf from 3.0.2 to 4.0.4"

packages/test-kit/src/with-feature.ts
eliminating that obscure error message:
replacing it with:
=> fix(test-kit): notify about a feature that can't be found

packages/electron-commons/src/initializers/electron-node.ts, packages/runtime-node/src/worker-thread-initializer.ts
revert graceful disposal of process back to termination, cause this changed caused huge performance degradation of disposal on some projects...
requires more investigation
=> fix: terminate process on exit instead of wait for dispose

packages/core/src/com/hosts/base-host.ts, packages/core/src/communication.feature.ts, packages/core/src/entities/env.ts, packages/core/src/entities/service.ts, packages/core/src/runtime-engine.ts, packages/core/test/node/env-dependencies.spec.ts
fixed a bug where services defined in inherited ENVs with allowRemote, did not in fact have a remote
=> fix: remote services provided from deep env

packages/core/package.json, packages/core/webpack.config.test.js
repo has it mixed with some packages executing from src while others from dist
=> test(core): execute tests from dist

packages/core/src/runtime-engine.ts
added timeout for engine runtime shutdown sequence
in case of a feature disposal failure, the shutdown will fail with an explicit timeout message with the feature id
=> chore: added per feature timeout for engine shutdown

packages/core/src/com/hosts/ws-client-host.ts, packages/electron-scripts/src/find-features.ts, packages/runtime-node/src/import-modules.ts, packages/runtime-node/src/node-environments-manager.ts, packages/runtime-node/src/remote-node-entry.ts, packages/scripts/src/application/application.ts, packages/scripts/src/config-middleware.ts, packages/scripts/src/engine-router.ts, packages/scripts/src/run-environment.ts, packages/test-kit/src/run-environment.ts, tsconfig.base.json
use Error.cause to reference original errors
can be further refactored for code reuse in many of these cases
=> feat: better error messages

packages/runtime-node/src/worker-thread-initializer.ts
@AviVahl Can I be the thing that makes the parallel tests flaky? #1896
=> fix: added com dispose for workerThreadInitializer

packages/runtime-node/src/core-node/create-application-metadata-provider.ts
missed in #1967. noticed right after squashing :/
=> fix: actually memoize the result

package.json, packages/core/package.json, packages/scripts/package.json, yarn.lock
- upgrade other dev-deps as well
- regenerate lock file
=> chore(deps): @wixc3/isomorphic-worker@1.2.5

packages/runtime-node/src/launch-http-server.ts, packages/runtime-node/src/node-environments-manager.ts, packages/runtime-node/test/node-com.unit.ts
=> fix(socket.io): use namespace import

packages/scripts/src/build-constants.ts
to make it easier to migrate to esm
also picking up cjs/mjs
=> refactor(scripts): identify cts/mts as code modules

packages/runtime-node/src/node-environments-manager.ts, packages/scripts/src/config-middleware.ts, packages/scripts/src/top-level-config-loader.ts, packages/scripts/src/utils/resolve-module-graph.ts
for compatibility with esm (in verbatimModuleSyntax mode)
=> refactor: mark type-only imports as such

packages/electron-scripts/src/commands/build.ts, packages/electron-scripts/src/commands/start.ts, packages/electron-scripts/src/engine-helpers.ts
=> refactor(electron-scripts): require -> import

test-fixtures/disconnecting-env/package.json
not need for the extra metadata in non-published test fixture
=> refactor(fixture): cleanup package.json

packages/engineer/src/cli.ts
rather than using require, use require.resolve which can easily be replaced with URL
=> refactor(engineer): self version read esm ready

packages/scripts/src/load-node-environment.ts, packages/scripts/src/run-environment.ts, packages/test-kit/src/run-environment.ts
- made `evaluateConfig` async and use dynamic import
- preparing for native esm
=> refactor(scripts): require -> import

packages/engineer/src/utils.ts
made `preRequire` a bit more ready for native esm
=> refactor(engineer): require -> import

packages/scripts/src/import-fresh.ts
now exposes any error it meets during evaluation
=> fix(import-fresh): actually reject caller

packages/core/package.json
to fix electron output, which generates a require to the .js
=> fix(core): allow importing features with .js

packages/scripts/src/utils/resolve-module-graph.ts
=> refactor(scripts): throw when cannot resolve

packages/runtime-node/src/launch-http-server.ts
fix for https://github.com/wixplosives/codux/issues/13458
=> fix: add hostname

packages/electron-scripts/src/commands/start.ts, packages/engineer/src/application-proxy-service.ts, packages/engineer/src/feature/dev-server.dev-server.env.ts, packages/engineer/src/utils.ts, packages/scripts/src/analyze-feature/find-features.ts, packages/scripts/src/analyze-feature/load-features-from-paths.ts, packages/scripts/src/application/application.ts, packages/scripts/src/types.ts, packages/scripts/src/utils/resolve-module-graph.ts
to allow working against sources
=> feat(config): support specifying extensions/conditions

packages/scripts/src/utils/resolve-module-graph.ts
This will improve feature analyze pref
=> feat: avoid analyzing type only imports and exports

packages/scripts/src/run-environment.ts
we're also planning to remove this overly complex way of passing data around in newer flow
=> fix(scripts): propagate requiredModules via metadata provider

packages/core/src/runtime-engine.ts
A possible issue of calling dispose twice on already disposing engine
=> fix: rerun dispose during disposal

packages/test-kit/src/with-feature.ts
Verbose log for `withFeature` disposal when running with `VERBOSE_DISPOSE` flag on
=> feat: verbose dispose

packages/scripts/src/run-environment.ts, packages/test-kit/src/run-environment.ts
Try to fix performance issues for tests that uses `getRunningFeature`
=> fix: try fix performance issue when running in tests

packages/engine-cli/src/cli.ts
fix parsing of cli boolean param
=> fix: cli bool param parsing

packages/engine-cli/src/cli.ts, packages/engine-cli/src/dashboard/dashboard.ts, packages/engine-cli/src/engine-build.ts, packages/test-kit/src/engine-app-manager.ts
this will allow to unify build / run / test flow 
+
Refactor to make the dashboard native html code nicer
=> feat: use same dir for test and run

packages/engine-cli/src/engine-app-manager.ts, packages/engine-cli/src/engine-build.ts, packages/engine-cli/src/index.ts, packages/engine-cli/src/launch-dashboard-server.ts, packages/engine-cli/src/read-metadata-files.ts, packages/engine-cli/src/resolve-build-configurations.ts, packages/engine-cli/src/run-local-mode-manager.ts
no changes to code just extracting to files
=> refactor: split engine-build

guides/docs/entities/environment/contextual.md, guides/docs/entities/environment/index.md, guides/docs/entities/feature/index.md, guides/docs/entities/index.md
And fixed some formatting of code blocks on feature guide
=> docs: improve environment and contextual environment guides

packages/runtime-node/src/node-env-manager.ts
use `ENGINE_GRACEFUL_TERMINATION=false` to disable graceful shutdown.
=> feat: allow to disable graceful shutdown with env variable

packages/test-kit/src/with-feature.ts
added in backward compatible way
=> feat: add npm to withFeature

packages/engine-cli/src/cli.ts, packages/engine-cli/src/create-entrypoints.ts, packages/engine-cli/src/engine-build.ts, packages/engine-cli/src/resolve-build-configurations.ts, packages/runtime-node/src/node-env-manager.ts
* electron build is now disabled by default. 
* allow run single worker environment and connect it to a MessagePort
=> feat: optional electron build and better env management 

lerna.json, package-lock.json, package.json
use `npm test` with `-ws` instead of lerna
=> refactor: remove lerna; use npm to run test

packages/core/src/com/logs.ts
Adding report error which will ignore errors that are being produced from EnvironmentDisconnected.
=> feat: report error which are not EnvironmentDisconnected

packages/core/src/com/logs.ts
Reverts wixplosives/engine#2513
per offline discussion with @matangeorgi
=> Revert "feat: report error which are not EnvironmentDisconnected"

packages/test-kit/src/with-feature.ts
needed for fixing https://github.com/wixplosives/codux/issues/21933
PR in codux https://github.com/wixplosives/codux/pull/21940 depends on this pr
Problem: currently screenshots are taken during the cleanup, but e2e tests in codux run withFeature with persist + have **nested describes** so the cleanup happens only once after all the test suits ran all the tests
Solution: expose api for taking screenshots so it can be called manually in afterEach hooks in codux
=> feat(test-kit): expose api for taking a screenshot

examples/cross-iframe/src/feature/configured-iframe.main.env.ts, packages/core/src/com/initializers/iframe.ts
Add the ability to post back run options after receiving the initial message.
=> feat(iframe init): change init handlers api

packages/engine-cli/src/create-environments-build-configuration.ts
fix issue where custom entry points was ts files.
=> feat: support ts source files as entry point

packages/runtime-node/src/node-env-manager.ts
set dev server port to running options so node environments can use it
=> feat(dev server port): set port to running options

package-lock.json, packages/runtime-node/src/node-env-manager.ts
in express@5, * comes in as an array, so join the parameters to get the config name
=> fix: correct config name resolution

packages/runtime-node/src/node-env-manager.ts
so it can launch envs from sources
=> feat: NodeEnvManager to use the same source extension to load envs
